{% set name = "indexed_bzip2" %}
{% set version = "1.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3fcdf8edf5d846c17d7200c024d447581a0723b55746d6fdcc610856ac33d42b

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  entry_points:
    - ibzip2 = indexed_bzip2:cli

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - setuptools >=46.4.0
    - wheel
    - cython >=0.29.24
  run:
    - python

test:
  imports:
    - indexed_bzip2
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/mxmlnkn/indexed_bzip2
  summary: Fast random access to bzip2 files
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE-MIT
    - LICENSE-APACHE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - ap--
    - mxmlnkn
