{% set name = "indexed_bzip2" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b4a7fda1d69d7d0650609cfffef598a5e07df59f152e0fa110fbdf1075e07673

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  entry_points:
    - ibzip2 = indexed_bzip2:cli

requirements:
  build:
    - {{ compiler('cxx') }}
    - sysroot_linux-64 2.17  # [linux64]
  host:
    - python
    - pip
    - cython
  run:
    - python

test:
  imports:
    - indexed_bzip2
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/mxmlnkn/indexed_bzip2
  summary: Fast random access to bzip2 files
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE-MIT
    - LICENSE-APACHE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - ap--
    - mxmlnkn
